name: Test

on: [push, pull_request]

jobs:
  unit-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Build-CppUtest
        run: |
          cd cpputest
          autoreconf . -i
          ./configure
          make tdd

      - name: Run the tests
        run: |
          cd unit-test && make
